apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: koko
build:
  artifacts:
  - image: us.gcr.io/koko-dev-323611/auth
    context: auth
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
